main: disable markup and highlight in log messages
wingtk/gvsbuild pull request #718
Opened 2022-10-24 22:15 UTC by saste

Disable rich markup and highlight, used by typer. Log/print messages do not assume any special formatting.

In particular, prevent failures when the output log contains unintended markup sequences, e.g. as in command:
$env:FOO = "/bar"
gvsbuild build --debug pixman

2022-10-25 11:10 UTC, danyeaw commented
Does this only cause issues when running a debug build? In general, having some color in the log output is quite nice.

2022-10-25 14:05 UTC, saste commented
> Does this only cause issues when running a debug build? In general, having some color in the log output is quite nice.

As far as I see, the coloring is completely random unless it is specifically crafted for rich, otherwise it might break randomly depending on what you print on the output or what you have on the environment.

2022-10-25 15:25 UTC, danyeaw commented
Have we seen this cause an error with a build? If you don't like the color at all, you can disable it with the `NO_COLOR` environmental variable.

2022-10-25 18:18 UTC, saste commented
If we want to keep colors and markup (which might well be worth), we should first make sure that the generated output complies with the [markup](https://rich.readthedocs.io/en/stable/markup.html) specification, and only then re-enable rich markup to avoid random escape issues.

In the meantime, I'd strongly go with this patch to fix the escape issues.

2022-10-26 01:36 UTC, danyeaw commented
@saste I am not able to reproduce any errors with `gvsbuild build --debug pixman`. I agree that the highlighting isn't perfect, but it isn't random. However, I still am trying to understand what the issue is before we turn it all off. Can you please better define what issues you are having?

2022-10-26 07:02 UTC, saste commented
>Can you please better define what issues you are having?

Sure.

```
PS src\gvsbuild> $env:foo = "/bar"
PS src\gvsbuild> gvsbuild build --debug pixman
Build type is release
[...]
Using Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
Running script "C:\Program Files (x86)\Microsoft Visual
Studio\2017\Professional\VC\Auxiliary\Build\vcvars64.bat"
Debug: vs env:ALLUSERSPROFILE -> [C:\ProgramData]
Debug: vs env:ChocolateyInstall -> [C:\ProgramData\chocolatey]
Debug: vs env:ChocolateyLastPathUpdate -> [133065241677366529]
Debug: vs env:CommandPromptType -> [Native]
Debug: vs env:CommonProgramFiles -> [C:\Program Files\Common Files]
Debug: vs env:CommonProgramFiles(x86) -> [C:\Program Files (x86)\Common Files]
Debug: vs env:CommonProgramW6432 -> [C:\Program Files\Common Files]
Debug: vs env:COMPUTERNAME -> [LIN-5CG9201M5P]
Debug: vs env:ComSpec -> [C:\WINDOWS\system32\cmd.exe]
Debug: vs env:DevEnvDir -> [C:\Program Files (x86)\Microsoft Visual
Studio\2017\Professional\Common7\IDE\]
Debug: vs env:DriverData -> [C:\Windows\System32\Drivers\DriverData]
Debug: vs env:ExtensionSdkDir -> [C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\sabatin\AppData\Local\Programs\Python\Python310\lib\site-packages\gvsbuild\build.py:428 │
│ in build                                                                                         │
│                                                                                                  │
│   425 │   │   │   v = opts.__dict__[co]                                                          │
│   426 │   │   │   pv = f"'{v}'" if type(v) is str else repr(v)                                   │
│   427 │   │   │   log.message_indent(f"'{co}': {pv}, ")                                          │
│ ❱ 428 │   builder = Builder(opts)                                                                │
│   429 │   builder.preprocess()                                                                   │
│   430 │                                                                                          │
│   431 │   to_build = __get_projects_to_build(opts)                                               │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │        archives_download_dir = WindowsPath('C:/gtk-build/src')                               │ │
│ │                    build_dir = WindowsPath('C:/gtk-build')                                   │ │
│ │                  capture_out = False                                                         │ │
│ │                   cargo_opts = None                                                          │ │
│ │                   check_hash = False                                                         │ │
│ │                        clean = False                                                         │ │
│ │                  clean_built = False                                                         │ │
│ │                           co = 'zip_continue'                                                │ │
│ │                configuration = <Configuration.release: 'release'>                            │ │
│ │                        debug = True                                                          │ │
│ │                         deps = True                                                          │ │
│ │                    enable_gi = False                                                         │ │
│ │                   export_dir = None                                                          │ │
│ │                   fast_build = False                                                         │ │
│ │            ffmpeg_enable_gpl = False                                                         │ │
│ │                 from_scratch = False                                                         │ │
│ │               git_expand_dir = None                                                          │ │
│ │                   keep_going = False                                                         │ │
│ │                   keep_tools = False                                                         │ │
│ │                   log_single = False                                                         │ │
│ │                     log_size = 0                                                             │ │
│ │                     make_zip = False                                                         │ │
│ │                 msbuild_opts = None                                                          │ │
│ │                     msys_dir = None                                                          │ │
│ │         net_target_framework = None                                                          │ │
│ │ net_target_framework_version = None                                                          │ │
│ │                   ninja_opts = None                                                          │ │
│ │                         opts = <gvsbuild.utils.base_project.Options object at                │ │
│ │                                0x000002425DB5ED10>                                           │ │
│ │                            p = 'pixman'                                                      │ │
│ │             patches_root_dir = WindowsPath('C:/Users/sabatin/AppData/Local/Programs/Python/… │ │
│ │                     platform = <Platform.x64: 'x64'>                                         │ │
│ │                    print_out = False                                                         │ │
│ │                     projects = ['pixman']                                                    │ │
│ │                    prop_file = WindowsPath('C:/Users/sabatin/AppData/Local/Programs/Python/… │ │
│ │                           pv = 'False'                                                       │ │
│ │                     py_wheel = False                                                         │ │
│ │                   python_dir = None                                                          │ │
│ │                   python_ver = <PythonVersion.py310: '3.10'>                                 │ │
│ │                  same_python = False                                                         │ │
│ │                         skip = []                                                            │ │
│ │               tools_root_dir = None                                                          │ │
│ │                      use_env = False                                                         │ │
│ │                            v = False                                                         │ │
│ │                      verbose = False                                                         │ │
│ │              vs_install_path = None                                                          │ │
│ │                       vs_ver = <VsVer.vs2022: '17'>                                          │ │
│ │                  win_sdk_ver = None                                                          │ │
│ │                 zip_continue = False                                                         │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\sabatin\AppData\Local\Programs\Python\Python310\lib\site-packages\gvsbuild\utils\builde │
│ r.py:126 in __init__                                                                             │
│                                                                                                  │
│    123 │   │   │   os.makedirs(se [...]

2022-10-27 01:01 UTC, danyeaw commented
@saste Thanks for the extra info. Is this `$env:foo = "/bar"` a valid use case for something? Why are we creating environmental variables that start with `/`?

2022-10-27 08:19 UTC, saste commented
> @saste Thanks for the extra info. Is this `$env:foo = "/bar"` a valid use case for something? Why are we creating environmental variables that start with `/`?

That's not the point, I picked this example but there are other similar cases when the env variables content can conflict with the assumed markup format.

1. You don't know what's in the user environment.
2. The program should not fail depending on the environment, especially if it's totally unrelated to the build.

You drive a car and it explodes at some point. You go to the vendor and complain. They tell you that this happened because you turned left three times in a row, you should never do it, the car was fine. No. The car should never explode in the first place.

To fix this, we either disable markup, or we correctly use markup (for example escaping values coming from the env variables, over which we have no control). The latter approach can be applied later, but my patch fixes the present issue.

2022-10-27 13:43 UTC, saste commented
To further elaborate (re-reading I realize this sounded too harsh, sorry for that), the problem for my use case stemmed from the fact that the CI where I use gvsbuild there are some variables with content of the type `/path/to/file`, and they conflict with the rich syntax. I could strip the paths, but it's more correct to disable rich syntax or to escape them in order to prevent the failure (the latter approach can be done as a second step since requires a bit more effort).

2022-10-28 23:54 UTC, danyeaw commented
@saste can you please provide an example of using an environment variable like this in your projects? Path definitions in Windows don't use /'s. Thanks!

2022-11-14 01:03 UTC, danyeaw commented
@saste Without a real world example of a project that has / in a variable that is broken by our fancy logging, I assume we have number 3 right now. Rich is heavily used by a ton of Python projects, I don't know of this being an issue. I am going to close this for now, but if we find a bug caused by this in a project, I would be glad to revisit it.

2022-11-17 17:59 UTC, saste commented
>@saste Without a real world example of a project that has / in a variable that is broken by our fancy logging, I assume we have number 3 right now. Rich is heavily used by a ton of Python projects, I don't know of this being an issue. I am going to close this for now, but if we find a bug caused by this in a project, I would be glad to revisit it.

It is failing in a work project because it is setting a variable with a linux path (since we have a multi-platform build environment), so this is a real world example. This could be easily fixed (and I'll do that), but still **the software should make no assumptions about the environment**, especially given that it is **legal** to have anything in the environment, so the fault here is on gvsbuild.

If you don't want to fix this, I'd go with fixing the log format to handle rich escaping in variables, but this issue is still outstanding so it should stay open.

2022-11-17 18:10 UTC, pbor commented
This seems a bit controversial and I do not have strong opinions... but I tend to agree with Stefano that having an env var that contains `/` is fairly common...

Maybe this was explained before, but when this happens: what is the effect? Just broken highlighting or does the entire build fail?

If it is just the highlighting, is there a way to reset the highlighter at the end of each project, so that we limit the broken highlighting to a section?

2022-11-17 18:11 UTC, saste commented
>Just broken highlighting or does the entire build fail?

Build fail.

2022-11-17 18:16 UTC, danyeaw commented
This shouldn't be controversial. I am just looking for an actual issue to be submitted. If there is an issue, let's fix it. If it is some theoretical issue, I don't think we should.

Can you please create an issue with your build environment variables? I don't understand why you are setting linux paths in Windows, but glad to learn.

2022-11-17 18:20 UTC, pbor commented
using / in Windows paths is legit. Also, who knows what else is in our users env... maybe the have `ROCK_BAND=AC/DC` :smile: 

I think we need to robust to this and not fail the entire build

2022-11-18 02:10 UTC, danyeaw requested changes

2022-11-18 02:10 UTC, danyeaw commented on gvsbuild/main.py
> +rich.reconfigure(markup=False, highlight=False)
If someone does have a / in an environment variable, and run with debug, then setting markup=False, but leaving highlight enabled will fix the issue without disabling the color functionality.

2022-12-15 11:11 UTC, AlessandroBono commented
Hi, can we close this since https://github.com/wingtk/gvsbuild/pull/757 has been merged?

2022-12-22 16:11 UTC, danyeaw commented
@pbor, are we ready to close this?

2022-12-24 09:52 UTC, closed without merging